-- Reset admin user permissions to secure defaults
UPDATE app_users SET 
    view_dashboard = 1,
    view_inventory = 1,
    view_logistics = 1,
    view_transit = 1,
    view_history = 1,
    view_admin = 1,
    view_settings = 1,
    view_backups = 1,
    view_usage = 1,
    view_stock_out = 1,
    inventory_access = 'RCUD',
    logistics_access = 'RCUD',
    transit_access = 'RCUD',
    history_access = 'RCUD',
    dashboard_access = 'RCUD',
    settings_access = 'RCUD',
    admin_access = 'RCUD',
    backups_access = 'RCUD',
    usage_access = 'RCUD',
    stock_out_access = 'RCUD',
    can_view_prices = 1,
    can_read = 1,
    can_create = 1,
    can_update = 1,
    can_delete = 1
WHERE username = 'admin';
