name = "asp-app-staging"
compatibility_date = "2024-03-04"
pages_build_output_dir = "public"
vars = { CF_ACCOUNT_ID = "e04d71a919de85594a6303a0aa4133e1" }

[[d1_databases]]
binding = "DB"
database_name = "aspstock-staging"
database_id = "39db27e3-c119-4545-b6f4-a7a6eeb2cce4"

[[r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "asp-stock-backups-staging"
